#!/bin/bash
set -e

help() {
  cat <<EOF
Usage: gh copr
Display an interactive list of open PRs. The selected PR is checked out.
Options:
    -r filter prs that need your review 
    --help show this message
Dependencies: fzf, gomplate
EOF
}

if ! git rev-parse --git-dir > /dev/null 2>&1; then
	echo "not a git repository"
	exit 1 
fi

# Make sure fzf is available
if ! type -p fzf >/dev/null; then
  echo "fzf not found on the system" >&2
  exit 1
fi

list_prs() {
  # shellcheck disable=SC2016
  gh api graphql --cache=5m -F owner='{owner}' -F repo='{repo}' -f query='
    query ($owner: String!, $repo: String!) {
      repository(owner: $owner, name: $repo) {
        pullRequests(first: 100, states: [OPEN]) {
          nodes {
            number
            title
            author {
              login
            }
            state
            headRefName
          }
        }
      }
    }
  ' --template '
    {{- range .data.repository.pullRequests.nodes -}}
      {{- .number | printf "#%.0f\t" | color "green" -}}
      {{- .title | printf "%s\t" -}}
      {{- .headRefName | printf "%s\t" | color "cyan" -}}
      {{- .author.login | printf " by %s\t" -}}
      {{- .state | printf "%s\n" -}}
    {{- end -}}
  ' | column -t -s$'\t'
}

pull_requests_that_need_my_review() {
	template='{{range(pluck "node" .data.search.edges) -}}
	{{tablerow (printf "\033[0;32m#%v\033[0m" .number) .title .author.login .headRefName -}}
	{{end -}}
	{{tablerender}}'

	query='query {
		search(query: "is:open is:pr review-requested:@me", type: ISSUE, first: 100) {
			edges {
				node {
					... on PullRequest {
						number
						title
						author {
							login
							... on User {
								name
							}
						}
						headRefName
					}
				}
			}
		}
	}'

	gh api graphql --paginate -f query="$query" -t "$template"
}

while test $# != 0; do
	case "$1" in
		--help|-h)
			help
			exit
			;;
		-r)
			selected=$(fzf --ansi <<<"$(pull_requests_that_need_my_review)")
			[ -n "$selected" ] || exit 1
			gh pr checkout "${selected%% *}"
			exit
			;;
		*)
			if [ -n "$VAR" ]; then
				help >&2
				exit 1
			fi
	esac
	shift
done

selected=$(fzf --ansi <<<"$(list_prs)")
[ -n "$selected" ] || exit 1
gh pr checkout "${selected%% *}"
