#!/bin/bash
set -e

help() {
	cat <<EOF
		Usage: gh copr
		Display an interactive list of open PRs. The selected PR is checked out.
		Options:
			-r filter prs that need your review 
			--help show this message
		Dependencies: fzf
EOF
}

if ! git rev-parse --git-dir > /dev/null 2>&1; then
	echo "not a git repository"
	exit 1 
fi

# Make sure fzf is available
if ! type -p fzf >/dev/null; then
	echo "fzf not found on the system, try:" 
	echo "brew install fzf"
	>&2
	exit 1
fi

pull_requests_that_need_my_review() {
	template='{{range(pluck "node" .data.search.edges) -}}
	{{tablerow (printf "\033[0;32m#%v\033[0m" .number) .title .author.login .headRefName -}}
	{{end -}}
	{{tablerender}}'

	query='query {
		search(query: "is:open is:pr review-requested:@me", type: ISSUE, first: 100) {
			edges {
				node {
					... on PullRequest {
						number
						title
						author {
							login
							... on User {
								name
							}
						}
						headRefName
					}
				}
			}
		}
	}'

	gh api graphql --paginate -f query="$query" -t "$template"
}

while test $# != 0; do
	case "$1" in
		--help|-h)
			help
			exit
			;;
		-r)
			selected=$(fzf --ansi <<<"$(pull_requests_that_need_my_review)")
			[ -n "$selected" ] || exit 1
			gh pr checkout "${selected%% *}"
			exit
			;;
		*)
			if [ -n "$VAR" ]; then
				help >&2
				exit 1
			fi
	esac
	shift
done

selected=$(fzf --ansi <<<"$(GH_FORCE_TTY=100% gh pr list | sed '1d;2d;3d;')")
[ -n "$selected" ] || exit 1
gh pr checkout "${selected%% *}"
